spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=remit
    username: sa
    password: Terefere123!
  jpa:
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
kafka:
  bootstrapAddress: localhost:9092

